site_name: gitStream 

site_description: Documentation of gitStream.
site_author: Ofer Affias

nav:
  - Overview: index.md
  - Getting started:
    - Installation: github-installation.md
    - GitHub app setup: github-app-setup.md
    - How it works: how-it-works.md
  - Examples: examples.md
  - Reference:
    - Editing the .cm file: editing-cm-file.md
    - Context variables: context-variables.md
    - Filter functions: filter-functions.md
    - Automation actions: automation-actions.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

theme:
  name: material
  logo: assets/gitstream-w.webp
  # When the user first visits your site, the media queries are evaluated in the order 
  # of their definition. The first media query that matches selects the default color palette.
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
      - header.autohide
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
markdown_extensions:
  - admonition
  - markdown.extensions.extra
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
extra:
  analytics:
    provider: google
    property: !ENV ANALYTICS_TAG
