name: Deploy to Cloudways

on:
  push:
    branches: [ "gh-pages" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3          
      - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # username
        username: master_rjwbgtdkqc
        # your sftp server
        server: 
        # your sftp server port, default to 22
        port: # default is 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: 
        # will put all file under this path
        local_path: # default is ./*
        # files will copy to under remote_path
        remote_path: applications/ewbccekaaz/public_html/docs/
        # connection via sftp protocol only
        sftp_only: # optional
        # sftp args
        sftpArgs: # optional
        # This operation will delete all files in the remote path before upload. Please be careful set this to true
        delete_remote_files: # optional
        # SSH passsword，If a password is set, the secret key pair is ignored
        password: PhWDZ8gB
