name: Deploy to Cloudways

on:
  push:
    branches: [ "gh-pages" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: master_rjwbgtdkqc
          # your sftp server
          server: 46.101.35.195
          # your sftp server port, default to 22
          port: 22
          # will put all file under this path
          local_path: ./*
          # files will copy to under remote_path
          remote_path: applications/ewbccekaaz/public_html/docs/
          # SSH passsword，If a password is set, the secret key pair is ignored
          password: PhWDZ8gB
