name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: ${{ ! endsWith(github.repository, '-dev') && 'docs.gitstream.cm' || '' }}
          ANALYTICS_TAG: ${{ ! endsWith(github.repository, '-dev') && 'G-PPEJMF05RD' || '' }}
            

